### ISSUE TITLE
Support local web interface?

### ISSUE THREAD

**Issue by jaytavares** [ngrok/ngrok-nodejs#62]
Maybe I'm wrong, but the local web interface that is available through the ngrok CLI tool doesn't seem to be available via the node agent. Is that right?

When I navigate to http://localhost:4040 there is nothing found.

Is there a way to enable the local web interface through the node agent? I can't find anything in the api docs.

**Comment by bobzilladev** [comment]
There is a solution on the roadmap for this, but currently the introspection interface is only available in the downloaded agent CLI.

**Comment by jaytavares** [comment]
Okay, thanks. I'll just spawn the CLI process in the meantime.
