### ISSUE TITLE
Can't run @ngrok/ngrok without `--optional` flag on `npm install`

### ISSUE THREAD

**Issue by neonexus** [ngrok/ngrok-nodejs#99]
I'm trying to move away from `ngrok` to the official `@ngrok/ngrok` package in my main open-source repo ([sails-react-bootstrap-webpack](https://github.com/neonexus/sails-react-bootstrap-webpack)). Just seems like the prudent move. However, right off the bat, I ran into an issue with `require('@ngrok/ngrok')`... 

```
Error: Cannot find module '@ngrok/ngrok-darwin-x64'
Require stack:
- /Users/neonexus/Sites/sails-react-boostrap-webpack/node_modules/@ngrok/ngrok/index.js
- /Users/neonexus/Sites/sails-react-boostrap-webpack/ngrok.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/Users/neonexus/Sites/sails-react-boostrap-webpack/node_modules/@ngrok/ngrok/index.js:127:29)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/neonexus/Sites/sails-react-boostrap-webpack/node_modules/@ngrok/ngrok/index.js',
    '/Users/neonexus/Sites/sails-react-boostrap-webpack/ngrok.js'
  ]
}
```

I am attempting to run this on my old Mac mini 2012. That I don't believe would be the issue. The issue, is more likely because I managed to find a way to run macOS Sonoma (most recent major version) on my mini (this particular model of Mac mini has been unsupported by Apple for years now).

Now, that all said, I don't know why the package wouldn't have installed `@ngrok/ngrok-darwin-x64` when it is clearly detecting the arch correctly...

Someone, please help!

**Comment by neonexus** [comment]
Ok, so this is a bit odd... I discovered that if I have `@ngrok/ngrok` listed in `optionalDependencies` and `npm i --optional`, then it installs everything correctly:

![Screenshot 2023-11-03 at 1 03 24 PM](https://github.com/ngrok/ngrok-nodejs/assets/305472/0b154f68-25d8-4c27-bdc2-50657b8bdb7f)

But, if I `npm i @ngrok/ngrok --save-dev`, then only the main package is installed, none of the native bindings come along (same with prod dependencies):

![Screenshot 2023-11-03 at 1 04 26 PM](https://github.com/ngrok/ngrok-nodejs/assets/305472/0e1e2f8a-ee2b-42ee-82e3-a45ea1724eff)

**Comment by neonexus** [comment]
Ok, I finally figured out my problem... My `.npmrc` file had `omit=optional` in it...

Closing...

**Comment by nijikokun** [comment]
Thanks for bringing attention to this and documenting the steps as you figured it out @neonexus ❤️  I'm sure others will find this useful if they run into the same issue.

Maybe there is something we can do here to make this clearer and easier for users.

**Comment by neonexus** [comment]
@nijikokun Something that might be a good / helpful change, is wrapping the native bindings `require` calls in a big try / catch; that way if something isn't installed (like with my case), then the package can throw out an error like "could not load native bindings... Are you excluding optional dependencies?"...

**Comment by neonexus** [comment]
@nijikokun I can't seem to figure out how it's getting generated, but inside of `index.js`, after the `switch (platform) {}`, there is this bit:

```javascript
if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}
```

This would work, if the `require()` call wasn't throwing an error. If the `switch` was wrapped in a silent `try / catch`, then the above code should handle the rest.
